"""The AI pictures for LF01 (../assets.py adds the house style: one bright subject on black, for the character look).
Nothing here shows a real person or a company's logo; places are generic."""
STILLS = [
    ("s02", "An endless aisle of tall library shelves made of server racks, thousands of tiny white status lights, seen from the floor looking down the aisle"),
    ("s03", "A swarm of hundreds of small glowing points of light moving in formation through a dark void, like a murmuration of starlings made of light"),
    ("s04", "A closed cardboard box standing on a black floor, bright white light leaking from every seam of its lid"),
    ("s05", "An empty exam hall in darkness, rows of desks fading into black, one desk lit by a hard overhead spotlight with a single exam paper on it"),
    ("s06", "A close-up of a glass padlock with a fine crack across it, bright light shining through the crack"),
    ("s07", "A wall covered with hundreds of padlocks of different shapes and sizes, lit from the side by hard raking light"),
    ("s08", "A heavy industrial lever switch on a steel control panel, pulled down, lit by a single hard spotlight"),
    ("s09", "A child's sandbox at night enclosed by a tall chain-link fence, lit by one floodlight from above, everything else black"),
    ("s10", "A grid of hundreds of identical small glass cubes floating in darkness, each with a tiny light inside, receding into the distance"),
    ("s11", "Two small glowing points of light far apart in darkness, joined by a single thin bright thread"),
    ("s12", "A dark wall covered edge to edge with hundreds of small paper notes pinned on top of each other, lit by hard raking light"),
    ("s13", "An old ornate brass key lying on black velvet, its edges glowing white in a hard spotlight"),
    ("s14", "A server room in darkness lit only by emergency lights, haze in the air, light falling across the racks"),
    ("s15", "A hedge labyrinth seen from directly above at night, one bright path of light traced from the centre to an opening in the outer wall"),
    ("s16", "A long concrete wall stretching into darkness with a single narrow doorway, brilliant light pouring through it onto the ground"),
    ("s19", "A single sheet of paper being fed into the glowing slot of a large dark machine, light spilling from the slot"),
    ("s20", "A network of round nodes connected by thin lines in darkness, a chain of nodes lit up bright one after another across the frame"),
    ("s21", "An open padlock hanging from the handle of a steel door in darkness, lit by a hard spotlight"),
    ("s22", "The large round lens of a security camera in darkness, a bright reflection in the glass, hard rim light on its housing"),
    ("s23", "The silhouette of a person seen from behind, sitting at a computer terminal in a dark room, the screen glowing white"),
    ("s24", "A laptop open on a desk at night, the screen glowing, a desk lamp and a cup beside it, the room in darkness"),
    ("s25", "A dark office at night, one computer monitor glowing brightly, light spilling over an empty office chair"),
    ("s26", "Two computer monitors facing each other across a dark table, both screens glowing white"),
    ("s27", "A handwritten note on a scrap of paper taped to the door of a server rack in darkness, lit by a single torch beam"),
    ("s28", "A robotic hand reaching out through the bars of a cage towards a point of light"),
    ("s29", "A worn dirt shortcut path cutting diagonally across a perfectly mown lawn between two paved paths, seen from above, low evening light"),
    ("s30", "A small speedboat turning a tight circle on black water, leaving a bright circular wake, seen from directly above"),
    ("s31", "A sealed envelope with a wax seal lying on a dark wooden desk under a hard spotlight"),
    ("s32", "The Earth seen from space at night, city lights glowing across the continents, the rest in darkness"),
    ("s33", "A long empty hospital records corridor at night, rows of filing cabinets, lit by cold overhead lights"),
    ("s34", "A tall hourglass standing on a black floor, the falling sand glowing, hard rim light on the glass"),
    ("s35", "A grand neoclassical government dome at night, floodlit against a black sky"),
    ("s36", "The wide steps and tall columns of a grand courthouse at night, floodlit, empty, black sky"),
    ("s37", "A sealed official envelope with a stamp, lying on a dark desk in the pool of light from a desk lamp"),
    ("s38", "Two people seen in silhouette facing each other across a table in a dark room, a single hard light between them"),
    ("c01", "A long corridor between tall server racks in darkness, rows of small white status lights receding to a vanishing point"),
    ("c02", "A dense swarm of glowing points flowing along the lines of a dark network, like light moving through veins"),
]
CLIPS = {
    "k01": ("c01", "The camera glides slowly forward down the corridor between the server racks; the status lights flicker."),
    "k02": ("c02", "The swarm of points of light flows and spreads along the network lines, branching outward."),
}
