"""The pictures for LF03 (../assets.py adds the house style). No real people, places, logos or products: the labs,
models and agencies are named on screen by labels, never shown."""
STILLS = [
    ("h01", "A sealed glass display case on a stone pedestal in a dark museum hall, a faint glowing core of light inside it"),
    ("h02", "A robotic hand reaching for the handle of a door left slightly ajar, light leaking through the gap, darkness around"),
    ("h03", "A security operations room at night, rows of empty desks facing a wall of glowing screens"),
    ("h04", "A magnifying glass held over a printed page of computer code, one line of the code glowing"),
    ("h05", "A folded newspaper with a blank front page on a dark desk under a lamp, a cup of coffee beside it"),
    ("h06", "A grand government building at night with tall stone columns and lit windows, an empty street in front"),
    ("h07", "Tall stacks of document boxes and files in a dark archive room, lit by a single desk lamp"),
    ("h08", "A technician seen from behind, sitting in front of three monitors filled with lines of code in a dark room"),
    ("h09", "A row of large industrial switches on a control panel, one of them being pulled down by a hand, hard light"),
    ("h10", "A chess piece stepping off the edge of a chessboard into darkness"),
    ("h11", "A transparent glass head in profile with a glowing network of fine light lines inside it, in darkness"),
    ("h12", "A strip of barrier tape stretched across a dark corridor, one end torn and hanging loose"),
    ("h13", "A small robot standing at a crossroads of glowing paths on a dark plain"),
    ("h14", "A heavy chain and padlock on a steel door, the chain cut through and hanging, hard light"),
    ("h15", "A trophy cup on a pedestal under a single spotlight in an empty dark hall"),
    ("h16", "An engineer's hands adjusting dials on a large analogue control board, hard light"),
    ("h17", "A plain black box on a table in a dark room, a thin crack of light glowing along the edge of its lid"),
    ("h18", "A long strip of paper covered in handwritten notes unrolling across a dark desk, lit by a lamp"),
    ("h19", "An empty office chair at a desk facing a window over a city at night, a laptop glowing on the desk"),
    ("h20", "A vast server hall at night, long aisles of racks lit by tiny status lights"),
    ("h21", "A queue line of brass posts and velvet rope winding through an empty dark lobby"),
    ("h22", "A metal key and a lock pick lying side by side on dark velvet, hard rim light"),
    ("h23", "Hands typing on a laptop keyboard in the dark, the screen lighting the fingers"),
    ("h24", "Two long lines of people seen from high above in a vast dark hall, walking in opposite directions, silhouettes only"),
    ("h25", "An empty meeting room with a long table and chairs, a single pendant lamp above it, at night"),
    ("h26", "An empty wooden witness table with a microphone in a dark hearing room, lit by one tall window"),
    ("h27", "A person's hands holding a smartphone in darkness, the screen lighting their fingers"),
    ("h28", "A thick printed report with a blank cover on a dark desk, a pair of reading glasses resting on it"),
    ("h29", "A wooden shipping crate sealed with tape alone on an empty warehouse floor, one light above it"),
    ("h30", "A glowing sphere of light locked inside a glass cube in a dark room"),
    ("c01", "A massive round steel vault door standing half open, light spilling out from inside, in darkness"),
    ("c02", "A loop of glowing fibre-optic strands twisting back through itself in darkness"),
]
CLIPS = {
    "k01": ("c01", "The heavy vault door swings slowly shut; the light from inside narrows to a thin line, then disappears."),
    "k02": ("c02", "Pulses of light race around the loop and fold back through it, over and over."),
}
