"""Builds ep03.py from the EP01 engine: the furniture (vertical setup, gauge, cards, captions, the drop and the
dream layer, the frame loop) is shared; the ruler, the floors and the cues come from ep03_parts.py."""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(HERE, "..", "ep01", "ep01.py")).read()
parts = open(os.path.join(HERE, "ep03_parts.py")).read()


def cut(s, start, end):
    i, j = s.index(start), s.index(end)
    assert i < j, (start, end)
    return s[:i], s[i:j], s[j:]


def section(s, start, end=None):
    i = s.index(start)
    return s[i:] if end is None else s[i:s.index(end, i)]


# 1. docstring + imports
doc_end = src.index('"""', 3) + 3
src = ('"""EP03 · THE SHOVEL SELLERS: the visual timeline (9:16, 1080×1920), Six Floors format.\n'
       'Generated by make_ep03.py from the EP01 engine plus ep03_parts.py. Edit those, then rerun make_ep03.py.\n\n'
       '    python3 ep03.py still 12 40 ...     # frames -> build/still_*.png\n'
       '    python3 ep03.py render              # build/ep03_silent.mp4 + build/events.json\n"""' + src[doc_end:])
assert "from script import FLOORS, LADDER, SOURCES" in src
src = src.replace("from script import FLOORS, LADDER, SOURCES", "from script import FLOORS, SOURCES\nLADDER = []")

# 2. the ruler: EP01's log-time ruler out, EP03's price ruler in
pre, _, post = cut(src, "RX0, RX1, RY = 96, 900, 1488", "def card(c, t):")
src = pre + section(parts, "RX0, RX1, RY", "# ================================================================ small drawing helpers") + "\n" + post

# 3. floors 0-3: EP01's out, EP03's (with helpers) in
pre, _, post = cut(src, "# ================================================================ floor 0 · GROUND", "ASC = None")
src = pre + section(parts, "# ================================================================ small drawing helpers",
                    "# ================================================================ floor 4 · IMAGINE") + "\n" + post

# 4. IMAGINE: keep the drop and the dream layer, swap EP01's ghosts and questions for EP03's
imag = section(src, "def fl_imagine(c, t):", "# ================================================================ floor 5 · SURFACE")
keep_until = '    c.drawRect(skia.Rect.MakeWH(W, H), mg.fill("#0B0C0E", 0.35))\n'
assert keep_until in imag
new_imag = imag[:imag.index(keep_until) + len(keep_until)] + "    dream_extras(c, t, kout)\n    h.vignette(c, 0.55)\n\n\n"
src = src.replace(imag, new_imag)
src = src.replace("# ================================================================ floor 5 · SURFACE",
                  section(parts, "def dream_extras(c, t, kout):", "# ================================================================ floor 5 · SURFACE") +
                  "\n# ================================================================ floor 5 · SURFACE", 1)

# 5. SURFACE and the cues
pre, _, post = cut(src, "def fl_surface(c, t):", "FLOOR_FN = [")
src = pre + section(parts, "def fl_surface(c, t):", "def build_cues():") + post
pre, _, post = cut(src, "def build_cues():", 'if __name__ == "__main__":')
src = pre + section(parts, "def build_cues():") + "\n\n" + post

# 6. the cards draw a trailing % small and raised (draw_big, in the parts)
old_card = "        c.drawString(big, cx + 30 - slide, cy + 66, fb, mg.fill(WHITE, a))\n"
assert old_card in src
src = src.replace(old_card, "        draw_big(c, big, cx + 30 - slide, cy + 66, fb, mg.fill(WHITE, a))\n")

# 7. names
src = src.replace('"EP01 · SIXTEEN HOURS", 540, 100', '"EP03 · THE SHOVEL SELLERS", 540, 100')
src = src.replace('"ep01_silent.mp4"', '"ep03_silent.mp4"')
open(os.path.join(HERE, "ep03.py"), "w").write(src)
print("wrote ep03.py", len(src.splitlines()), "lines")
